# Fleet inventory — students may extend this
all:
  children:
    app_servers:
      hosts:
        sdc-app-1:
          ansible_host: localhost
          ansible_port: 2261
        sdc-app-2:
          ansible_host: localhost
          ansible_port: 2262
        sdc-app-3:
          ansible_host: localhost
          ansible_port: 2263
        sdc-app-4:
          ansible_host: localhost
          ansible_port: 2264
    load_balancers:
      hosts:
        sdc-lb:
          ansible_host: localhost
          ansible_port: 2265
    monitoring:
      hosts:
        sdc-monitor:
          ansible_host: localhost
          ansible_port: 2266
  vars:
    ansible_ssh_private_key_file: .ssh/cadet_key
